### ISSUE TITLE
Some questions about my running error

### ISSUE THREAD

**Issue by RakuSetsuna** [NickCH-K/causalgraphs#2]
Hi Nicks,

Although I am a bit shame, but I still want to ask,
I always get this error when I run the last code.
> animate(p,nframes=200)
Error in file(what, "rb") : cannot open the connection                                                                
In addition: There were 50 or more warnings (use warnings() to see the first 50)
------------------------------------
Is it the reason for the Conflicts?
> library(tidyverse)
-- Attaching packages --------------------------------------- tidyverse 1.2.1 --
√ ggplot2 3.0.0     √ purrr   0.2.5
√ tibble  1.4.2     √ dplyr   0.7.7
√ tidyr   0.8.2     √ stringr 1.3.1
√ readr   1.1.1     √ forcats 0.3.0
-- **Conflicts** ------------------------------------------ tidyverse_conflicts() --
x dplyr::filter() masks stats::filter()
x dplyr::lag()    masks stats::lag()

Thanks，
Raku

**Comment by NickCH-K** [comment]
Hmm, I'm not sure what's going on there; I don't get the same error. It looks like it's having difficulty opening up a connection to a temporary file which gganimate might need. Perhaps something to do with file permissions? Try changing the working directory to something you know you have write access to and give it another go.
